#!/bin/bash
# Build a macOS .app bundle for the Job Application Tracker
# Run this script once to create the app.

set -e

APP_NAME="Job Tracker"
BUNDLE_ID="com.arnoldancheril.jobtracker"
PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
APP_DIR="$PROJECT_DIR/${APP_NAME}.app"

echo "Building ${APP_NAME}.app ..."

# Remove old bundle if exists
rm -rf "$APP_DIR"

# Create bundle structure
mkdir -p "$APP_DIR/Contents/MacOS"
mkdir -p "$APP_DIR/Contents/Resources"

# Create Info.plist
cat > "$APP_DIR/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>${APP_NAME}</string>
    <key>CFBundleDisplayName</key>
    <string>${APP_NAME}</string>
    <key>CFBundleIdentifier</key>
    <string>${BUNDLE_ID}</string>
    <key>CFBundleVersion</key>
    <string>2.0</string>
    <key>CFBundleShortVersionString</key>
    <string>2.0</string>
    <key>CFBundleExecutable</key>
    <string>launcher</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>LSMinimumSystemVersion</key>
    <string>10.13</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>LSUIElement</key>
    <false/>
</dict>
</plist>
PLIST

# Create launcher script — embed absolute paths so the .app works from anywhere.
# We hardcode both the project dir and the python interpreter path so that
# Finder (which uses a minimal PATH) can always find them.
PYTHON_PATH="$(command -v python3)"
cat > "$APP_DIR/Contents/MacOS/launcher" <<LAUNCHER
#!/bin/bash
# Job Tracker launcher – auto-generated by build_app.sh

PROJECT_DIR="$PROJECT_DIR"
PYTHON="$PYTHON_PATH"

cd "\$PROJECT_DIR"

# Install deps if needed (first run only)
if ! "\$PYTHON" -c "import PyQt5" 2>/dev/null; then
    "\$PYTHON" -m pip install -r requirements.txt --quiet 2>/dev/null
fi

exec "\$PYTHON" main.py
LAUNCHER

chmod +x "$APP_DIR/Contents/MacOS/launcher"

# Create a simple icon using Python
"$PROJECT_DIR/../../../.." 2>/dev/null || true
PYTHON=$(command -v python3 || echo "/usr/bin/python3")

"$PYTHON" - "$APP_DIR/Contents/Resources" <<'PYICON'
import sys, os

resources_dir = sys.argv[1]

# Create an iconset directory
iconset_dir = os.path.join(resources_dir, "AppIcon.iconset")
os.makedirs(iconset_dir, exist_ok=True)

try:
    from PIL import Image, ImageDraw, ImageFont
    has_pil = True
except ImportError:
    has_pil = False

if has_pil:
    sizes = [16, 32, 64, 128, 256, 512]
    for size in sizes:
        img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
        draw = ImageDraw.Draw(img)
        
        # Background circle
        margin = int(size * 0.05)
        draw.ellipse([margin, margin, size - margin, size - margin],
                     fill=(99, 102, 241))  # indigo-500
        
        # Briefcase emoji approximation - white rectangle
        bw = int(size * 0.45)
        bh = int(size * 0.35)
        bx = (size - bw) // 2
        by = (size - bh) // 2 + int(size * 0.05)
        draw.rounded_rectangle([bx, by, bx + bw, by + bh],
                               radius=int(size * 0.05),
                               fill="white")
        # Handle
        hw = int(size * 0.2)
        hh = int(size * 0.08)
        hx = (size - hw) // 2
        hy = by - hh + 2
        draw.rounded_rectangle([hx, hy, hx + hw, hy + hh],
                               radius=int(size * 0.03),
                               outline="white", width=max(1, size // 64))
        
        for scale in [1, 2]:
            actual = size * scale
            resized = img.resize((actual, actual), Image.LANCZOS)
            suffix = f"_{size}x{size}" if scale == 1 else f"_{size}x{size}@2x"
            resized.save(os.path.join(iconset_dir, f"icon{suffix}.png"))
    
    print("Icon images created with PIL")
else:
    # Create minimal PNG files without PIL (1x1 pixel PNGs)
    # This is a valid minimal PNG
    import struct, zlib
    def minimal_png(width, height, r, g, b):
        def chunk(chunk_type, data):
            c = chunk_type + data
            return struct.pack(">I", len(data)) + c + struct.pack(">I", zlib.crc32(c) & 0xFFFFFFFF)
        
        raw = b""
        for y in range(height):
            raw += b"\x00"  # filter none
            for x in range(width):
                raw += bytes([r, g, b, 255])
        
        compressed = zlib.compress(raw)
        
        signature = b"\x89PNG\r\n\x1a\n"
        ihdr = chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
        idat = chunk(b"IDAT", compressed)
        iend = chunk(b"IEND", b"")
        
        return signature + ihdr + idat + iend
    
    sizes = [16, 32, 128, 256, 512]
    for size in sizes:
        png_data = minimal_png(size, size, 99, 102, 241)
        for scale in [1, 2]:
            if scale == 2 and size * 2 > 1024:
                continue
            suffix = f"_{size}x{size}" if scale == 1 else f"_{size}x{size}@2x"
            with open(os.path.join(iconset_dir, f"icon{suffix}.png"), "wb") as f:
                f.write(png_data if scale == 1 else minimal_png(size * 2, size * 2, 99, 102, 241))
    
    print("Minimal icon images created")

print("Iconset ready at:", iconset_dir)
PYICON

# Convert iconset to icns (macOS built-in tool)
ICONSET_DIR="$APP_DIR/Contents/Resources/AppIcon.iconset"
if [ -d "$ICONSET_DIR" ] && command -v iconutil &>/dev/null; then
    iconutil -c icns "$ICONSET_DIR" -o "$APP_DIR/Contents/Resources/AppIcon.icns" 2>/dev/null || true
    rm -rf "$ICONSET_DIR"
    echo "Icon converted to .icns"
fi

echo ""
echo "✅  ${APP_NAME}.app created successfully!"
echo ""
echo "To use:"
echo "  1. Double-click '${APP_NAME}.app' in Finder to launch"
echo "  2. Drag it to your Dock for quick access"
echo "  3. Or move it to /Applications for system-wide access"
echo ""
echo "Location: $APP_DIR"
