#!/bin/bash

# Application Tracker Global Launcher Installation Script
# This script creates a global command to launch the Application Tracker from anywhere

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAUNCHER_NAME="apptracker"
LAUNCHER_PATH="/usr/local/bin/$LAUNCHER_NAME"

echo "Installing Application Tracker global launcher..."

# Create the global launcher script
sudo tee "$LAUNCHER_PATH" > /dev/null << EOF
#!/bin/bash
# Application Tracker Global Launcher
# Generated by install_launcher.sh

cd "$APP_DIR"
if command -v python3 &> /dev/null; then
    python3 main.py
elif command -v python &> /dev/null; then
    python main.py
else
    echo "Error: Python is not installed or not in PATH"
    echo "Please install Python 3 to run the Application Tracker"
    exit 1
fi
EOF

# Make the launcher executable
sudo chmod +x "$LAUNCHER_PATH"

echo "✅ Application Tracker launcher installed successfully!"
echo ""
echo "You can now launch the Application Tracker from anywhere by typing:"
echo "   $LAUNCHER_NAME"
echo ""
echo "Examples:"
echo "   $LAUNCHER_NAME                    # Launch the app"
echo "   open ~/Desktop/ApplicationTracker.app   # Launch via desktop icon"
echo ""
echo "The desktop app is also available at: ~/Desktop/ApplicationTracker.app" 