# Generated by Django 5.1.1 on 2024-10-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bot_performance_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='risk_level',
            field=models.CharField(choices=[('Low Risk', 'Low Risk'), ('Medium Risk', 'Medium Risk'), ('High Risk', 'High Risk')], default='Medium Risk', max_length=20),
        ),
    ]
