# Generated by Django 5.1.1 on 2024-10-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bot_risk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='greek_values',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='bot',
            name='sample_trades',
            field=models.JSONField(default=list),
        ),
    ]
