"""
Model V15 Under - Specialized UNDER NBA Props Prediction Model
================================================================

**PLACEHOLDER FOR FUTURE DEVELOPMENT**

This is the UNDER-specialized model of a dual-model approach:
- Model V15 General: Focuses on OVER picks + can suggest strong UNDER picks
- Model V15 Under: Focuses EXCLUSIVELY on UNDER opportunities (this file)

NOTE: The General model already handles strong UNDER picks. This specialized
model will be developed to provide even more UNDER opportunities with 
additional factors not covered in the General model.

WHY A SEPARATE UNDER MODEL?
---------------------------
Analysis from extensive backtesting revealed:
1. PTS UNDER hits at 63.9% vs PTS OVER at 48.3% (HUGE difference!)
2. Negative factors compound more reliably than positive ones
3. Elite defense consistently limits production across positions
4. Cold streaks persist longer than hot streaks due to psychology

KEY INSIGHTS FOR FUTURE DEVELOPMENT:
------------------------------------
1. DEFENSE VS POSITION (From Under Model V2 and V10):
   - Elite defense (top 5) = ~62% UNDER hit rate
   - Elite defense + Cold streak = ~66% UNDER hit rate
   
2. COLD STREAK PERSISTENCE:
   - Players don't immediately snap out of slumps
   - L5 < Season avg = continued underperformance expected
   
3. COMPOUNDING FACTORS:
   - Multiple negative factors = premium picks
   - Elite defense + Cold streak + B2B = highest confidence

4. PROP-SPECIFIC INSIGHTS:
   - PTS UNDER: 63.9% (primary focus)
   - REB UNDER: 59% (good secondary option)
   - AST UNDER: Volatile, only for specific players

PLANNED MODEL V15 UNDER FEATURES:
---------------------------------
1. More aggressive UNDER detection
2. Lower edge thresholds for strong defense matchups
3. Factor scoring system with weighted contributions
4. Injury rust detection (first games back)
5. Historical player vs team analysis
6. Blowout risk detection (reduces star minutes)

Author: NBA Props Team - Model V15
Created: February 2026
Version: 15.0
Status: PLACEHOLDER - To be fully implemented later
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Optional, List, Dict, Any
from pathlib import Path

from ..db import Db
from ..paths import get_paths

from .model_v15_shared import (
    LineInfo,
    PlayerStatsV15,
    DefenseContextV15,
    BackToBackInfo,
    MODEL_VERSION,
)


# ============================================================================
# Configuration (Placeholder)
# ============================================================================

@dataclass
class ModelConfigV15Under:
    """
    Model V15 Under Configuration.
    
    PLACEHOLDER - To be fully developed.
    
    This model will specialize in UNDER picks with:
    - Factor-based scoring system
    - Defense-first approach
    - Cold streak persistence detection
    - B2B fatigue integration
    """
    # === VERSION INFO ===
    model_name: str = "Model V15 Under"
    model_version: str = MODEL_VERSION
    status: str = "PLACEHOLDER"
    
    # === PLANNED SETTINGS (To be tuned) ===
    min_games_required: int = 10
    min_avg_minutes: float = 20.0  # Slightly lower for more coverage
    
    # Defense thresholds
    elite_defense_rank: int = 5
    good_defense_rank: int = 10
    
    # Cold streak thresholds
    cold_streak_severe_pct: float = -20.0
    cold_streak_mild_pct: float = -10.0
    
    # Edge requirements
    min_edge_sportsbook: float = 5.0  # Lower bar for defense plays
    min_edge_derived: float = 8.0
    
    # Factor weights (to be validated)
    weights: Dict[str, int] = field(default_factory=lambda: {
        "defense_elite": 30,
        "defense_good": 15,
        "cold_streak_severe": 22,
        "cold_streak_mild": 12,
        "b2b_second": 8,
        "injury_first_back": 18,
        "high_variance": 6,
    })
    
    def to_dict(self) -> Dict:
        return {k: v for k, v in self.__dict__.items() if not k.startswith('_')}


# ============================================================================
# Data Classes (Placeholder)
# ============================================================================

@dataclass
class PropPickV15Under:
    """A pick generated by Model V15 Under. PLACEHOLDER."""
    player_id: int
    player_name: str
    team_abbrev: str
    opponent_abbrev: str
    game_date: str
    prop_type: str
    line: float
    line_source: str
    projection: float
    edge_pct: float
    factors: Dict[str, bool] = field(default_factory=dict)
    factor_score: int = 0
    confidence_score: float = 0.0
    confidence_tier: str = "STANDARD"
    reasons: List[str] = field(default_factory=list)
    
    # Results (for backtesting)
    actual_value: Optional[float] = None
    hit: Optional[bool] = None


@dataclass
class DailyPicksV15Under:
    """All UNDER picks for a day. PLACEHOLDER."""
    date: str
    games: int
    picks: List[PropPickV15Under] = field(default_factory=list)
    status: str = "PLACEHOLDER - Not yet implemented"
    
    def summary(self) -> str:
        return f"""
{'='*70}
MODEL V15 UNDER - {self.date}
{'='*70}
STATUS: {self.status}

This model is a placeholder for future development.
The Model V15 General already handles strong UNDER picks.

For UNDER predictions, use:
    from src.nba_props.engine.model_v15_general import get_daily_picks_v15_general
    picks = get_daily_picks_v15_general("{self.date}")
    under_picks = picks.under_picks
{'='*70}
"""


# ============================================================================
# Public API (Placeholder)
# ============================================================================

def get_daily_picks_v15_under(
    game_date: str,
    config: Optional[ModelConfigV15Under] = None,
    db_path: Optional[Path] = None,
) -> DailyPicksV15Under:
    """
    PLACEHOLDER - Get UNDER picks for a date.
    
    This function is a placeholder. For UNDER picks, use the General model:
    
        from src.nba_props.engine.model_v15_general import get_daily_picks_v15_general
        picks = get_daily_picks_v15_general(game_date)
        under_picks = picks.under_picks
    
    Args:
        game_date: Date string (YYYY-MM-DD)
        config: Optional configuration (not used in placeholder)
        db_path: Optional database path (not used in placeholder)
    
    Returns:
        DailyPicksV15Under with placeholder status
    """
    return DailyPicksV15Under(
        date=game_date,
        games=0,
        picks=[],
        status="PLACEHOLDER - Use Model V15 General for UNDER picks",
    )


def run_backtest_v15_under(
    start_date: str,
    end_date: str,
    config: Optional[ModelConfigV15Under] = None,
    db_path: Optional[Path] = None,
    verbose: bool = False,
) -> Dict[str, Any]:
    """
    PLACEHOLDER - Run backtest for Model V15 Under.
    
    This function is a placeholder. For UNDER backtest analysis, 
    use the General model and filter for UNDER picks:
    
        from src.nba_props.engine.model_v15_general import run_backtest_v15_general
        result = run_backtest_v15_general(start_date, end_date)
        print(f"UNDER picks: {result.under_hits}/{result.under_picks}")
    
    Returns:
        Dict with placeholder status
    """
    return {
        "status": "PLACEHOLDER",
        "message": "Use Model V15 General backtest and filter for UNDER picks",
        "start_date": start_date,
        "end_date": end_date,
    }


# ============================================================================
# CLI Entry Point
# ============================================================================

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Model V15 Under - PLACEHOLDER")
    parser.add_argument("--date", help="Date for picks (YYYY-MM-DD)")
    parser.add_argument("--backtest-start", help="Backtest start date")
    parser.add_argument("--backtest-end", help="Backtest end date")
    parser.add_argument("--verbose", "-v", action="store_true")
    
    args = parser.parse_args()
    
    print("=" * 70)
    print("MODEL V15 UNDER - PLACEHOLDER")
    print("=" * 70)
    print()
    print("This model is a placeholder for future development.")
    print()
    print("The Model V15 General already handles strong UNDER picks.")
    print("To get UNDER predictions, use:")
    print()
    print("    from src.nba_props.engine.model_v15_general import get_daily_picks_v15_general")
    print("    picks = get_daily_picks_v15_general('2026-02-03')")
    print("    under_picks = picks.under_picks")
    print()
    print("For backtesting UNDER performance:")
    print()
    print("    from src.nba_props.engine.model_v15_general import run_backtest_v15_general")
    print("    result = run_backtest_v15_general('2025-12-01', '2026-02-02')")
    print("    print(f'UNDER: {result.under_hits}/{result.under_picks}')")
    print()
    print("=" * 70)
